# This is a GitHub actions workflow for the NCEPLIBS-bacio project.
#
# This workflow does the intel compiler build.
#
# Ed Hartnett 1/19/23
name: Intel
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  Intel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compilers: ["oneapi", "classic"]

    steps:

    - name: "Install Intel"
      uses: NOAA-EMC/ci-install-intel-toolkit@develop
      with:
        compiler-setup: ${{ matrix.compilers }}
      
    - name: "Checkout bacio"
      uses: actions/checkout@v4

    - name: "Build bacio"
      run: |
        cmake -B build
        cmake --build build --parallel 2 --verbose
    
    - name: "Test bacio"
      run: |
        set -e
        ctest --test-dir build --verbose --output-on-failure --rerun-failed


