# This is a GitHub actions workflow for the NCEPLIBS-bacio project.
#
# This workflow does the Linux build.
#
# Ed Hartnett 1/19/23
name: Linux
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  Linux:
    runs-on: ubuntu-latest
    env:
      FC: gfortran-11
      CC: gcc-11

    steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: build
      run: |
        cmake -B build
        cmake --build build --parallel 2 --verbose

    - name: test
      run: |
        set -e
        ctest --test-dir build --output-on-failure --rerun-failed --verbose

        
