# This is a GitHub actions workflow for the NCEPLIBS-bacio project.
#
# This workflow does the MacOS build.
#
# Ed Hartnett 1/19/23
name: MacOS
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  MacOS:
    runs-on: macos-latest
    env:
      FC: gfortran-12
      CC: gcc-12
    strategy:
      matrix:
        shared: [ON, OFF]

    steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: build
      run: |
        cmake -B build -DBUILD_SHARED_LIBS=${{ matrix.shared }} -DCMAKE_INSTALL_PREFIX=~/install
        cmake --build build --parallel 2 --verbose
        cmake --install build
        ls -l ~/install
        ls -l ~/install/lib
    
    - name: test
      run: |
        set -e
        ctest --test-dir build --verbose --output-on-failure --rerun-failed

        
