name: Validate PR

on:
  pull_request:
    types: [opened, synchronize, reopened, review_requested, edited]
  pull_request_review:
    types: [submitted]

jobs:
  validate:
    permissions:
      pull-requests: read
    uses: AlexanderRichert-NOAA/ci-validate-pr/.github/workflows/validate-pr.yaml@fc63090f13db5db7344905b541eb53508f21352e
    with:
      validate-genai-disclosure: true
