name: Validate PR

on:
  pull_request:
    types: [opened, synchronize, reopened, review_requested, edited]
  pull_request_review:
    types: [submitted]

jobs:
  Checks:
    permissions:
      pull-requests: read
    uses: AlexanderRichert-NOAA/ci-validate-pr/.github/workflows/validate-pr.yaml@d08192f8b6a0a226811366133bde23ee3a0b8e56
    with:
      validate-genai-disclosure: true
