name: Validate PR

on:
  pull_request:
    types: [opened, synchronize, reopened, review_requested]
  pull_request_review:
    types: [submitted]

jobs:
  validate:
    uses: NOAA-EMC/ci-validate-pr/.github/workflows/validate-pr.yaml@0afc4eba3aa7ba7ea1ded6f97388f99ca57f7355
    with:
      validate-genai-disclosure: true
      approvals-for-external-contributors: 2
      approvals-for-critical-changes: 2
      critical-file-count: 10
